### ISSUE TITLE
Error conversion stdObject to a string in Topvisor\TopvisorSDK\V2\Page.php

### ISSUE THREAD

**Issue by AndrewDanilov** [topvisor/topvisor-sdk#2]
In **\Topvisor\TopvisorSDK\V2\Page.php**
in method **getErrorsString()**
you use construction on line 137:

`$errorsString[] = $error->string.($error->code?" ($error->code)":'').($error->detail?": $error->detail":'');`

Where `$error->detail` is stdObject and can not be converted to string in php >8.1. And we get an error about that when trying to use method **getErrorsString()**

Version of topvisor/topvisor-sdk is 2.5

**Comment by Artemeey** [comment]
fixed: https://github.com/topvisor/topvisor-sdk/releases/tag/v2.6
